"""create chess tournament module

Revision ID: 20260711_0011
Revises: 20260711_0010
Create Date: 2026-07-11
"""
from alembic import op
import sqlalchemy as sa

revision = "20260711_0011"
down_revision = "20260711_0010"
branch_labels = None
depends_on = None

def upgrade():
    tables = set(sa.inspect(op.get_bind()).get_table_names())
    if "chess_tournaments" not in tables:
        op.create_table("chess_tournaments", sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("venue",sa.String(255)),sa.Column("tournament_date",sa.Date),sa.Column("organizer",sa.String(180)),sa.Column("chief_arbiter",sa.String(180)),sa.Column("system",sa.String(20),nullable=False,server_default="swiss"),sa.Column("number_of_rounds",sa.Integer,nullable=False,server_default="5"),sa.Column("max_participants",sa.Integer),sa.Column("is_published",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("is_locked",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime,nullable=False))
    if "chess_age_groups" not in tables:
        op.create_table("chess_age_groups",sa.Column("id",sa.Integer,primary_key=True),sa.Column("tournament_id",sa.Integer,sa.ForeignKey("chess_tournaments.id"),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("description",sa.Text),sa.Column("gender_rule",sa.String(20),nullable=False,server_default="open"),sa.Column("admin_name",sa.String(120)),sa.Column("is_published",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime,nullable=False),sa.UniqueConstraint("tournament_id","name",name="uq_chess_age_group_name")); op.create_index("ix_chess_age_groups_tournament","chess_age_groups",["tournament_id"])
    if "chess_participants" not in tables:
        op.create_table("chess_participants",sa.Column("id",sa.Integer,primary_key=True),sa.Column("age_group_id",sa.Integer,sa.ForeignKey("chess_age_groups.id"),nullable=False),sa.Column("player_code",sa.String(32),nullable=False),sa.Column("fide_id",sa.String(30)),sa.Column("name",sa.String(180),nullable=False),sa.Column("gender",sa.String(20)),sa.Column("date_of_birth",sa.Date),sa.Column("district",sa.String(100)),sa.Column("state",sa.String(100)),sa.Column("school",sa.String(220)),sa.Column("club",sa.String(180)),sa.Column("mobile",sa.String(25)),sa.Column("email",sa.String(180)),sa.Column("photo",sa.String(250)),sa.Column("status",sa.String(20),nullable=False,server_default="pending"),sa.Column("checked_in",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("withdrawn",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime,nullable=False),sa.UniqueConstraint("age_group_id","player_code",name="uq_chess_player_code")); op.create_index("ix_chess_participant_search","chess_participants",["age_group_id","name"]); op.create_index("ix_chess_participant_fide","chess_participants",["fide_id"])
    if "chess_rooms" not in tables:
        op.create_table("chess_rooms",sa.Column("id",sa.Integer,primary_key=True),sa.Column("age_group_id",sa.Integer,sa.ForeignKey("chess_age_groups.id"),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("board_start",sa.Integer,nullable=False,server_default="1"),sa.Column("board_end",sa.Integer,nullable=False,server_default="50"),sa.UniqueConstraint("age_group_id","name",name="uq_chess_room_name")); op.create_index("ix_chess_rooms_age_group","chess_rooms",["age_group_id"])
    if "chess_rounds" not in tables:
        op.create_table("chess_rounds",sa.Column("id",sa.Integer,primary_key=True),sa.Column("age_group_id",sa.Integer,sa.ForeignKey("chess_age_groups.id"),nullable=False),sa.Column("round_number",sa.Integer,nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="draft"),sa.Column("is_published",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime,nullable=False),sa.Column("published_at",sa.DateTime),sa.UniqueConstraint("age_group_id","round_number",name="uq_chess_round_number")); op.create_index("ix_chess_rounds_age_group","chess_rounds",["age_group_id"])
    if "chess_pairings" not in tables:
        op.create_table("chess_pairings",sa.Column("id",sa.Integer,primary_key=True),sa.Column("round_id",sa.Integer,sa.ForeignKey("chess_rounds.id"),nullable=False),sa.Column("board_number",sa.Integer,nullable=False),sa.Column("table_number",sa.Integer),sa.Column("room_id",sa.Integer,sa.ForeignKey("chess_rooms.id")),sa.Column("white_player_id",sa.Integer,sa.ForeignKey("chess_participants.id"),nullable=False),sa.Column("black_player_id",sa.Integer,sa.ForeignKey("chess_participants.id")),sa.Column("result",sa.String(30)),sa.Column("score_status",sa.String(20),nullable=False,server_default="pending"),sa.Column("remarks",sa.Text),sa.Column("submitted_by",sa.String(120)),sa.Column("submitted_at",sa.DateTime),sa.Column("approved_by",sa.String(120)),sa.Column("approved_at",sa.DateTime),sa.UniqueConstraint("round_id","board_number",name="uq_chess_board_round")); op.create_index("ix_chess_pairings_round","chess_pairings",["round_id"]); op.create_index("ix_chess_pairings_players","chess_pairings",["white_player_id","black_player_id"])
    if "chess_standings" not in tables:
        op.create_table("chess_standings",sa.Column("id",sa.Integer,primary_key=True),sa.Column("age_group_id",sa.Integer,sa.ForeignKey("chess_age_groups.id"),nullable=False),sa.Column("participant_id",sa.Integer,sa.ForeignKey("chess_participants.id"),nullable=False),sa.Column("points",sa.Float,nullable=False,server_default="0"),sa.Column("wins",sa.Integer,nullable=False,server_default="0"),sa.Column("draws",sa.Integer,nullable=False,server_default="0"),sa.Column("losses",sa.Integer,nullable=False,server_default="0"),sa.Column("buchholz",sa.Float,nullable=False,server_default="0"),sa.Column("rank",sa.Integer),sa.Column("updated_at",sa.DateTime),sa.UniqueConstraint("age_group_id","participant_id",name="uq_chess_standing_player")); op.create_index("ix_chess_standings_group","chess_standings",["age_group_id","rank"])
    if "chess_orbiters" not in tables:
        op.create_table("chess_orbiters",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("username",sa.String(80),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("is_active",sa.Boolean,nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime,nullable=False),sa.UniqueConstraint("username",name="uq_chess_orbiter_username"))
    if "chess_room_assignments" not in tables:
        op.create_table("chess_room_assignments",sa.Column("id",sa.Integer,primary_key=True),sa.Column("orbiter_id",sa.Integer,sa.ForeignKey("chess_orbiters.id"),nullable=False),sa.Column("room_id",sa.Integer,sa.ForeignKey("chess_rooms.id"),nullable=False),sa.UniqueConstraint("orbiter_id","room_id",name="uq_chess_orbiter_room")); op.create_index("ix_chess_room_assignment_orbiter","chess_room_assignments",["orbiter_id"])
    if "chess_announcements" not in tables:
        op.create_table("chess_announcements",sa.Column("id",sa.Integer,primary_key=True),sa.Column("tournament_id",sa.Integer,sa.ForeignKey("chess_tournaments.id"),nullable=False),sa.Column("age_group_id",sa.Integer,sa.ForeignKey("chess_age_groups.id")),sa.Column("title",sa.String(200),nullable=False),sa.Column("message",sa.Text,nullable=False),sa.Column("is_pinned",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("is_published",sa.Boolean,nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime,nullable=False)); op.create_index("ix_chess_announcements_tournament","chess_announcements",["tournament_id"])
    if "chess_audit_logs" not in tables:
        op.create_table("chess_audit_logs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("tournament_id",sa.Integer,sa.ForeignKey("chess_tournaments.id"),nullable=False),sa.Column("action",sa.String(100),nullable=False),sa.Column("entity_type",sa.String(50)),sa.Column("entity_id",sa.Integer),sa.Column("actor",sa.String(120)),sa.Column("ip_address",sa.String(64)),sa.Column("details",sa.Text),sa.Column("created_at",sa.DateTime,nullable=False)); op.create_index("ix_chess_audit_tournament","chess_audit_logs",["tournament_id","created_at"])
    # Reserved extension tables keep the schema compatible with board, score, result, prize and certificate workflows.
    for name in ("chess_boards","chess_games","chess_scores","chess_tie_breaks","chess_results","chess_prizes","chess_certificates","chess_settings"):
        if name not in tables: op.create_table(name, sa.Column("id",sa.Integer,primary_key=True), sa.Column("tournament_id",sa.Integer,sa.ForeignKey("chess_tournaments.id"),nullable=False), sa.Column("data",sa.Text), sa.Column("created_at",sa.DateTime))

def downgrade():
    tables = set(sa.inspect(op.get_bind()).get_table_names())
    for name in ("chess_settings","chess_certificates","chess_prizes","chess_results","chess_tie_breaks","chess_scores","chess_games","chess_boards","chess_audit_logs","chess_announcements","chess_room_assignments","chess_orbiters","chess_standings","chess_pairings","chess_rounds","chess_rooms","chess_participants","chess_age_groups","chess_tournaments"):
        if name in tables: op.drop_table(name)
